sudo: required

os: linux

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=2.2.2

before_install:
  - curl -L https://github.com/docker/compose/releases/download/v2.2.2/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - docker-compose up -d
  - docker ps
  - docker tag dz3_api:latest mishanko/pet-project:api_3
  - docker push mishanko/pet-project:api_3

script:
  - docker exec dz3_api_1 python test.py

after_script:
  - docker-compose down

branches:
  only:
    - master
