os: linux

language: python

python:
  - 3.8

install:
  - pip install -r requirements-dev.txt

env:
  - DOCKER_COMPOSE_VERSION=3.8

before_install:
  - sudo rm -rf /usr/local/bin/docker-compose
  - sudo apt-get install python3-pip
  - sudo pip3 install docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - docker-compose build 
  - docker tag dz3_worker:latest mishanko/pet-project:api_3
  - docker push mishanko/pet-project:api_3

script:
  - python test.py

branches:
  only:
    - master

