os: linux

language: python

python:
  - 3.8

install:
  - pip install -r requirements-dev.txt

env:
  - DOCKER_COMPOSE_VERSION=3.8

before_install:
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - /usr/local/bin/docker-compose build
  - docker tag dz3_worker:latest mishanko/pet-project:api_3
  - docker push mishanko/pet-project:api_3

scripts:
  - python test.py

branches:
  only:
    - master

