sudo: required

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=2.2.1

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - sudo apt install docker-compose

before_script:
  - docker-compose up -d
  - docker ps
  - docker tag dz3_api:latest mishanko/pet-project:api_3
  - docker push mishanko/pet-project:api_3

script:
  - docker exec dz3_api_1 python test.py

after_script:
  - docker-compose down

branches:
  only:
    - master
