version: '3.8'

services:
  api:
    # image: mishanko/pet-project:api_3
    build: .
    volumes:
      - ./app/models:/usr/src/app/app/models
      - ./app/mlflow/mlflow.db:/usr/src/app/mlflow/mlflow.db
      - ./app/mlflow/mlartifacts:/usr/src/app/mlflow/mlartifacts
      - ./logs:/usr/src/app/logs
    ports:
      - 8080:8080

    restart: always

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ./config/grafana.ini:/etc/grafana/grafana.ini
    links:
      - prometheus

  mlflow:
    image: atcommons/mlflow-server
    build: ./app/mlflow/.
    ports:
      - 5000:5000
    environment:
      BACKEND_URI: sqlite:///mlflow.db
      ARTIFACT_ROOT: /artifacts
    volumes:
      - ./app/mlflow:/usr/src/app/mlflow
      - ./app/models:/usr/src/app/app/models
