version: '3.8'

services:
  api:
    build: .
    volumes:
      - ./worker/models:/usr/src/app/worker/models
      - ./logs:/usr/src/app/logs
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - mongodb
      - redis
      - worker

  mongodb:
    image: mongo:latest

  worker:
    build: ./worker 
    volumes:
      - ./worker/models:/usr/src/app/worker/models
    depends_on:
      - redis
  
  redis:
    image: redis

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
    links:
      - prometheus
