version: '3.8'

services:
  api:
    image: mishanko/dz3_api:third_DZ
    volumes:
      - ./worker/models:/usr/src/app/worker/models
      - ./logs:/usr/src/app/logs
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - mongodb
      - redis
      - worker

  mongodb:
    image: mongo:latest

  worker:
    image: mishanko/dz3_worker:third_DZ
    volumes:
      - ./worker/models:/usr/src/app/worker/models
    depends_on:
      - redis
  
  redis:
    image: redis
