version: '3.8'

services:
  api:
    build: .
    volumes:
      - ./worker/models:/usr/src/app/worker/models
      - ./worker/mlflow:/mlflow
      - ./logs:/usr/src/app/logs
    ports:
      - 8080:8080
      - 5000:5000
    restart: always
    depends_on:
      - redis
      - worker
    links:
      - mlflow

  worker:
    build: ./worker 
    volumes:
      - ./worker/models:/usr/src/app/worker/models
    depends_on:
      - redis
  
  redis:
    image: redis

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ./config/grafana.ini:/etc/grafana/grafana.ini
    links:
      - prometheus

  mlflow:
    image: atcommons/mlflow-server
    volumes:
      - ./worker/mlflow:/mlflow
    environment:
      BACKEND_URI: sqlite:////mlflow/mlflow.db
      ARTIFACT_ROOT: /mlflow/artifacts